import node from '../public/node.jpg';

export const theCabin = {
  name: 'The Cabin',
  image: node,
  imageAlt: 'An image of a cabin',
  slug: 'thecabin',
  summary: 'This cabin offers 1250 square feet of indoor living space and an incredible 800 square foot deck with panoramic views. The house is an elevated split level with three bedrooms, two baths, an open floor plan living room, dining room, and kitchen. Rooms are furnished and include high-speed internet, utilities, and cleaning service.',
  amenities: [
    'Private bedroom with queen bed, desk space, and closet',
    'High-speed internet',
    'En-suite or shared bathroom with shower and bathtub',
    'Towels, linens, blankets, pillows',
    'Soap, shampoo, toilet paper',
    'Coffee, tea, spices, and other kitchen essentials',
    'Washer & dryer',
    'Full kitchen with refrigerator, freezer, oven, stove, microwave, dishwasher, coffee maker, coffee grinder, and toaster',
    'Furnished dishes, utensils, pots & pans, baking equipment',
    'Wrap-around deck with lounge chairs, hammock, and outdoor BBQ grill',
    'Lending library',
    'Ping pong table',
    'Board games',
    'Indoor fireplace',
    'HDTV with Netflix',
    'Heating & air-conditioning',
    'Smoke alarms, carbon monoxide detectors, fire extinguishers',
    'Private water & septic',
  ],
}

import containerImage from '../public/containerCabin.jpg';

export const theContainer = {
  name: 'The Container',
  image: containerImage,
  imageAlt: 'An arial view of the container cabin',
  slug: 'thecontainer',
  summary: 'This cabin was designed from the ground up for a community of remote workers. It’s a 4-suite shipping container cabin with giant front and back decks, private entrances for each room, and beautiful modern interiors. The suites, office nooks, community spaces, and decks were all custom-built in partnership with Forte Shelter for the needs of remote workers. Rooms are furnished and include high-speed internet, utilities, and cleaning service.',
  amenities: [
    'Private suites with queen bed, office nook, and wardrobe',
    'En-suite bathroom with shower',
    'High-speed internet',
    'Private entrance to bedroom suite',
    'Towels, linens, blankets, pillows',
    'Soap, shampoo, toilet paper',
    'Coffee, tea, spices, and other kitchen essentials',
    'Washer & dryer',
    'Private suites with queen bed, office nook, and wardrobe',
    'En-suite bathroom with shower',
    'High-speed internet',
    'Private entrance to bedroom suite',
    'Towels, linens, blankets, pillows',
    'Soap, shampoo, toilet paper',
    'Coffee, tea, spices, and other kitchen essentials',
    'Washer & dryer',
    'Full kitchen with refrigerator, freezer, oven, stove, microwave, dishwasher, coffee maker, coffee grinder, and toaster',
    'Furnished dishes, utensils, pots & pans, baking equipment',
    'Multiple decks with lounge chairs, hammock, and outdoor BBQ grill',
    'Lending library',
    'Board games',
    'Heating & air-conditioning',
    'HDTV with Netflix',
    'Smoke alarms, carbon monoxide detectors, fire extinguishers',
    'Private water & septic',
  ],
}