import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/home/Hero'
import SideImage from '../components/home/SideImage'
import Spark from '../components/home/Spark'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Hero />
        <SideImage />
        <Spark />
      </main>
      <footer>
      </footer>
    </div>
  )
}


