import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/home/Hero'
import Vision from '../components/home/Vision'
import Reality from '../components/home/Reality'
import Spark from '../components/home/Spark'
import Contribute from '../components/home/Contribute'
import Past from '../components/home/Past'
import Join from '../components/home/Join'
import Collaborate from '../components/home/Collaborate'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Hero />
        <Vision />
        <Reality />
        <Contribute />
        <Spark />
        <Join />
        <Past />
        <Collaborate />
      </main>
      <footer>
      </footer>
    </div>
  )
}


